### ISSUE TITLE
Implement SymbolicLink for Windows

### ISSUE THREAD

**Issue by adswa** [jacobstanley/unix-compat#46]
A few disclaimers: 
- Thanks for providing this package! 
- **I don't have any experience with or knowledge of Haskell**. I'm part of a dev team for a Python software that builds on git-annex (written in Haskell). Anything in this issue may be completely bullocks (and I apologize in advance should that be the case).

At the moment, Symbolic links seem to be unsupported:
https://github.com/jacobstanley/unix-compat/blob/9a6758eeacb9ee3597011fcf5a92985c06c1fa57/src/System/PosixCompat/Files.hsc#L382-L390

However, the System.Win32 package seems to expose Symbolic Link functionality: https://hackage.haskell.org/package/Win32-2.10.1.0/docs/System-Win32-SymbolicLink.html.

When browsing through past issues and PRs of this repo, I found https://github.com/jacobstanley/unix-compat/issues/20 and the corresponding implementation in https://github.com/jacobstanley/unix-compat/pull/29 by @joeyh, and (again, sorry for not knowing any Haskell at all) these looked similar enough that I was hopeful that support for symlinks could be done in a similar way.

With a bit of guidance I would be motivated to help, if I can. I don't have testing infrastructure at the moment, but I could try to set it up.

**Comment by jacobstanley** [comment]
Apologies for the late reply!

My main concern would be around using the Win32 API in the right way. I don't have a windows box to test on anymore.

If you could find the right Win32 calls to make to implement the API (in C for example). I'd be happy to help translate that to Haskell.

It seems like this may be a concern for you, from the linked documentation:
```
 you should worry about UAC (User Account Control) when use this module's function in your application:

require to use 'Run As Administrator' to run your application.
or modify your application's manifect file to add <requestedExecutionLevel level=requireAdministrator uiAccess=false/>.
```

**Comment by jacobstanley** [comment]
Apologies for the late reply!

Making the call to this API seems simple enough but we have to know if it's a file or directory which is a bit annoying. It would be interesting to know what other languages do in a similar situation.

It also seems like this may be a concern, from the linked documentation:
```
 you should worry about UAC (User Account Control) when use this module's function in your application:

- require to use 'Run As Administrator' to run your application.
- or modify your application's manifect file to add <requestedExecutionLevel level=requireAdministrator uiAccess=false/>.

Starting from Windows 10 version 1703 (Creators Update), after enabling Developer Mode, users can create symbolic links without requiring the Administrator privilege in the current process. Supply a True flag in addition to the target and link name to enable this behavior. 
```

**Comment by jacobstanley** [comment]
It would definitely be useful to do an implementation in `git-annex` itself first if there isn't one already so we can see if it works for its primary purpose.

**Comment by jacobstanley** [comment]
Fixed in https://github.com/jacobstanley/unix-compat/pull/54
