### ISSUE TITLE
Build with GHC 9.2.1

### ISSUE THREAD

**Issue by pepeiborra** [jacobstanley/unix-compat#52]
I am getting this build error:

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/26626/147337469-dd0e61af-a5cc-4015-9231-c450a478dfd0.png">

https://github.com/haskell/haskell-language-server/runs/4625279018?check_suite_focus=true#step:15:838

**Comment by jneira** [comment]
I am trying #47 with hls and it seems to work

**Comment by andreasabel** [comment]
Maybe `unix-compat-0.5.1` needs an upper bound on `Win32` just like https://hackage.haskell.org/package/unix-compat-0.5.2/revisions/ ?

**Comment by andreasabel** [comment]
On a Windows machine,
```
cabal install -w ghc-9.2.2 unix-compat-0.5.1
```
fails nowadays already in the configuration step.

I think this issue can be closed.
