### ISSUE TITLE
Please add tag for 0.6

### ISSUE THREAD

**Issue by andreasabel** [jacobstanley/unix-compat#55]
Having the tags complete at https://github.com/jacobstanley/unix-compat/tags is great for seeing the diff between versions.

**Comment by jacobstanley** [comment]
Done! Looks like I had missed pushing the .cabal changes too

**Comment by andreasabel** [comment]
Thanks!
I realized that 0.5.4 is also not tagged, would be great to have a complete tag list for the most recent releases...

**Comment by jacobstanley** [comment]
Done!
