### ISSUE TITLE
Support `unix-2.8.0.0`

### ISSUE THREAD

**Issue by mitchellwrosen** [jacobstanley/unix-compat#61]
I've opened #62 as one solution, and there's an alternative solution here #60

**Comment by andreasabel** [comment]
@jacobstanley Supporting `unix-2.8` becomes more relevant now that GHC 9.6 alpha is out which bundles `unix-2.8.0.0`.

**Comment by ysangkok** [comment]
@mitchellwrosen , FYI you're listed on [the maintainers list](https://hackage.haskell.org/package/unix-compat/maintainers/) now

**Comment by mitchellwrosen** [comment]
Yep! Release forthcoming. We're deciding where to house the new repo since I don't have write access to this one.

**Comment by mitchellwrosen** [comment]
Done in https://github.com/haskell-pkg-janitors/unix-compat and released to Hackage as `unix-compat-0.7`
