### ISSUE TITLE
Offer to help maintain this package

### ISSUE THREAD

**Issue by mitchellwrosen** [jacobstanley/unix-compat#63]
Hey! I'd like to offer to help maintain this package, if you are interested.

**Comment by mitchellwrosen** [comment]
Friendly ping

**Comment by andreasabel** [comment]
@mitchellwrosen : This is very much appreciated, I think a version of `unix-compat` working with `unix-2.8` is urgently needed.

I sent the following email now (2023-01-18) to `jacob stanley io`:

> Dear Jacob,
>
> thank you for maintaining unix-compat!
>
> The current unix-compat-0.6 does not work together with unix-2.8 which will soon become mandatory (GHC 9.6 alpha is already out).
>
> Would you be able to release unix-compat-0.7 which works with unix-2.8 soon?  This would greatly help the Haskell community to prepare for GHC 9.6!
>
> If you are not available now, maybe you can accept help?  It has been offered here:
>
>  https://github.com/jacobstanley/unix-compat/issues/63
>
> There is also already a PR fixing the problem:
>
>   https://github.com/jacobstanley/unix-compat/pull/62
>
> The minimal action needed to get a co-maintainer going is to add them on Hackage:
>
>   https://hackage.haskell.org/package/unix-compat/maintainers/
>
> (But preferably also give them write access to github.com/jacobstanley/unix-compat.)
>
> Best regards,
> Andreas

**Comment by mitchellwrosen** [comment]
Thanks for doing that @andreasabel, any response?

**Comment by andreasabel** [comment]
> Thanks for doing that @andreasabel, any response?

No.  I think you can go to step 2 of the [takeover recipe](https://wiki.haskell.org/Taking_over_a_package):
> State your intention to take over the package in a public forum (we recommend the haskell-cafe and/or libraries list). CC the maintainer.

**Comment by mitchellwrosen** [comment]
Thanks for the link, I've sent an email to `haskell-cafe@haskell.org`

**Comment by mitchellwrosen** [comment]
... well, I tried to, but I don't see my email anywhere in the archives: https://mail.haskell.org/pipermail/haskell-cafe/2023-February/thread.html

So maybe it has to be manually approved by someone first, or maybe I don't understand how mailing lists work. 🤷‍♂️

**Comment by andreasabel** [comment]
I didn't receive your email either on haskell-cafe.  
But you had posts there previously, last in 2016, with id: Mitchell Rosen (mitchellwrosen gmail com).

**Comment by mitchellwrosen** [comment]
I'm not sure what to make of that. Here's a screenshot of the email I sent, which didn't bounce or anything.

<img width="1493" alt="Screen Shot 2023-02-04 at 4 35 30 PM" src="https://user-images.githubusercontent.com/1074598/216790499-596d9330-e0c0-4011-9a4c-811e41bb4efd.png">

<img width="419" alt="Screen Shot 2023-02-04 at 4 36 58 PM" src="https://user-images.githubusercontent.com/1074598/216790542-2fa1e631-8fe4-4352-a95e-524da9b3e2ac.png">

**Comment by andreasabel** [comment]
Maybe just resend it, to both the cafe and the libraries list.  I also looked at https://discourse.haskell.org/ but it seems takeover requests are not published there.

**Comment by andreasabel** [comment]
Takeover request announced 2023-02-04 on Haskell cafe: https://mail.haskell.org/pipermail/haskell-cafe/2023-February/135910.html

`unix-compat` has ~4000 indirect dependencies according to Hackage:
> 79 direct, 3945 indirect [[details](https://hackage.haskell.org/package/unix-compat-0.6/)]

**Comment by andreasabel** [comment]
@mitchellwrosen [proceeded with the next step](https://mail.haskell.org/pipermail/haskell-cafe/2023-February/135946.html) on 2023-02-21.
> Send an email to the hackage administrators ([hackage-admin@haskell.org](mailto:hackage-admin@haskell.org)), with a link to the public email thread.

**Comment by mitchellwrosen** [comment]
Hehe, thanks for taking the minutes during all of this @andreasabel

**Comment by gbaz** [comment]
added to maintainers. 👍

**Comment by mitchellwrosen** [comment]
Excellent, thank you!

**Comment by andreasabel** [comment]
@mitchellwrosen : You can do a hackage upload now.  But hopefully @jacobstanley will show up for one of these:
1. Take up maintenance again.
2. Add you as co-maintainer here on this repo with write access.
3. Transfer this repo to a new location where you have write & admin access.

This is to ensure the continuity of issue numbers, for instance.

**Comment by mitchellwrosen** [comment]
Indeed, that would be great. However, in the meantime, I don't see a great path forward other than forking the repo and pointing people away from this one.

**Comment by andreasabel** [comment]
@mitchellwrosen : Consider moving it to an organization like `unix-compat` or `unix-compat-hs` or so.  Like I did in https://github.com/blaze-builder/blaze-builder .  Then you can have co-maintainers on par.  Having fallback maintainers for important packages like this one is anyway a good idea.

**Comment by mitchellwrosen** [comment]
@andreasabel Good idea. What do you think about making an org to house both of these orphaned packages, and possibly others? Something like `haskell-community/`?

**Comment by andreasabel** [comment]
In this case, it could maybe go directly to https://github.com/haskell (it already has `unix`).

Or, if you prefer a less ambitious home, https://github.com/orgs/haskell-pkg-janitors .  This one started out great, but currently only has `haskell-src` actively maintained (and lots of passive founding members).
I would prefer reactivating `haskell-pkg-janitors` over making a new organisation with similar goals.

Btw. see discussion at 
- https://github.com/haskellfoundation/stability/pull/12

@mitchellwrosen : I sent you an invitation to `haskell-pkg-janitors` in case you choose this one.

**Comment by mitchellwrosen** [comment]
Great, `haskell-pkg-janitors` sounds like an excellent home for now.

**Comment by mitchellwrosen** [comment]
@andreasabel Can you please make me an owner of `haskell-pkg-janitors`? As a member, I can't make a new repo

**Comment by andreasabel** [comment]
Ok, did that!
